### PR TITLE
README: update for Homebrew lua instructions

### PR DESCRIPTION
**Pull request by DomT4**
Re #554.

### CODE REVIEW

**Comment by szymonkaliski** [comment]
Is this change really needed? I just reinstalled Lua with latest homebrew version, and haven't change anything, and could install all `mjolnir.*` things I use...? (that's only about `~/.luarocks/config.lua` vs `/usr/local/etc/luarocks52/config-5.2.lua`, everything else is obviously needed) :)

**Comment by DomT4** [comment]
There's not much controversial here:

` brew install luarocks ` = Removed because that formula no longer exists.
` mkdir -p ~/.luarocks ` = Removed because the new Luarocks has hardcoded config dirs to facilitate side-by-side usage.
` echo 'rocks_servers = { "http://rocks.moonscript.org" }' > /usr/local/etc/luarocks52/config-5.2.lua ` = Said new config dir for the standard Lua installation.

**Comment by szymonkaliski** [comment]
Yeah, I just prefer keeping settings like that in `~/...` instead in `/usr/...`, maybe put both as alternatives?

**Comment by szymonkaliski** [comment]
Actually on my system there's already something in there:

```bash
> cat /usr/local/etc/luarocks52/config-5.2.lua
rocks_trees = {
   { name = [[system]], root = [[/usr/local]] }
}
```

And if you're using `>` you're overwriting that...

**Comment by DomT4** [comment]
> maybe put both as alternatives?

Can't. Doesn't play nicely with the potential for multiple Lua/Luarocks setups. ` etc ` is a fairly widely accepted sysconfdir.

> Actually on my system there's already something in there:

Yes, Homebrew put it there.

> And if you're using > you're overwriting that...

Indeed. I'd much prefer to use ` >> `. I didn't write the original README though, and the original README is written so it'd overwrite anything that was previously in that file.

**Comment by sdegutis** [comment]
@DomT4 The original readme was pointing to a presumably non-existent file, and the update is pointing to a confirmed-existing file, so it should use `>>`.

**Comment by DomT4** [comment]
Cool. Thanks for the feedback. Will change.

**Comment by sdegutis** [comment]
Thanks.

**Pull request merged**
