### PR TITLE
Change `https` to `http` (former doesn't work).

### PR DESCRIPTION
**Pull request by janaspage**

### CODE REVIEW

**Comment by sdegutis** [comment]
@janaspage Seems more like the right solution is to contact LuaRocks.org and let them know their SSL certificate is broken so they can fix it right away.

**Comment by Habbie** [comment]
Cert looks fine from here, by the way.

**Comment by janaspage** [comment]
Here's what I see:

pic 2015-11-24 at 13 02 26

**Comment by Habbie** [comment]
Ah - somehow I ended up at luarocks.org before, not rocks.moonscript.org. I recommend updating to this link: https://luarocks.org/search?q=mjolnir

**Comment by sdegutis** [comment]
@Habbie Nice detective work. @janaspage Can you change the link per his suggestion in your PR?

**Comment by janaspage** [comment]
PR changed.

**Comment by sdegutis** [comment]
@janaspage @Habbie Thanks both of you! :cake:

**Pull request merged**
