### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by salutis**

### CODE REVIEW

**Comment by sdegutis** [comment]
Why 64px?

**Comment by salutis** [comment]
The original image is 128x128, retina is 2x. 128 / 2 = 64. Tested on real retina HW.

**Comment by sdegutis** [comment]
But now it's so *tiny*.

**Comment by salutis** [comment]
Yeah, the next step is to generate a 256x256 bitmap and update the markup to 128x128. :)

**Pull request merged**
